### ISSUE TITLE
Error: Column schema in domain but not in data

### ISSUE THREAD

**Issue by madi** [ryan112358/nist-synthetic-data-2021#7]
Hi! I'm trying your tool for creating a synthesized population. I have converted all my variable to categorical. I read that id is not supported and cardinality should be less than 1000 and preferable less than 100, but I have one column with 181 different classes. 
My dataframe is  1035201 rows x 35 columns
After preprocessing, when I run 

python extensions/check_domain.py --dataset $PATH_TO_discretized_csv --domain $PATH_TO_parameters_json

I get:

Error: Column schema in domain but not in data

The domain file looks like this:

{"PUMA": 181, "YEAR": 7, "GQ": 5, "SEX": 2, "AGE": 73, "MARST": 6, "RACE": 9, "HISPAN": 5, "CITIZEN": 4, "SPEAKENG": 5, "HCOVANY": 2, "HCOVPRIV": 2, "HINSEMP": 2, "HINSCAID": 2, "HINSCARE": 2, "EDUC": 11, "EMPSTAT": 3, "EMPSTATD": 6, "LABFORCE": 2, "WRKLSTWK": 3, "ABSENT": 3, "LOOKING": 3, "AVAILBLE": 4, "WRKRECAL": 3, "WORKEDYR": 3, "DEPARTS": 151, "ARRIVES": 10, "HHWT_bins": 10, "PERWT_bins": 10, "INCTOT_bins": 10, "INCWAGE_bins": 10, "INCWELFR_bins": 10, "INCINVST_bins": 10, "INCEARN_bins": 10, "POVERTY_bins": 10}

I don't understand what is wrong with the data, looks ok to me. How do I check?

Thank you in advance.

**Comment by madi** [comment]
I've tried also dropping the "PUMA" column but the error persists

**Comment by litlep-nibbyt** [comment]
Thanks for reaching out. Could you provide the list of columns of the dataframe that you're working with?

**Comment by madi** [comment]
Hi @meijiu Thank you for answering. At moment I made another tentative, as I was changing the names of the columns when binning the variables. Now I kept the same. so, the names of the columns in the dataframe are:

'PUMA', 'YEAR', 'HHWT', 'GQ', 'PERWT', 'SEX', 'AGE', 'MARST', 'RACE','HISPAN', 'CITIZEN', 'SPEAKENG', 'HCOVANY', 'HCOVPRIV', 'HINSEMP',  'HINSCAID', 'HINSCARE', 'EDUC', 'EMPSTAT', 'EMPSTATD', 'LABFORCE', 'WRKLSTWK', 'ABSENT', 'LOOKING', 'AVAILBLE', 'WRKRECAL', 'WORKEDYR',  'INCTOT', 'INCWAGE', 'INCWELFR', 'INCINVST', 'INCEARN', 'POVERTY',  'DEPARTS', 'ARRIVES'

and the current domain file is:

{"PUMA": 181, "YEAR": 7, "HHWT": 25, "GQ": 5, "PERWT": 25, "SEX": 2, "AGE": 73, "MARST": 6, "RACE": 9, "HISPAN": 5, "CITIZEN": 4, "SPEAKENG": 5, "HCOVANY": 2, "HCOVPRIV": 2, "HINSEMP": 2, "HINSCAID": 2, "HINSCARE": 2, "EDUC": 11, "EMPSTAT": 3, "EMPSTATD": 6, "LABFORCE": 2, "WRKLSTWK": 3, "ABSENT": 3, "LOOKING": 3, "AVAILBLE": 4, "WRKRECAL": 3, "WORKEDYR": 3, "INCTOT": 20, "INCWAGE": 20, "INCWELFR": 20, "INCINVST": 15, "INCEARN": 19, "POVERTY": 25, "DEPARTS": 25, "ARRIVES": 25}

I still get the same error though

**Comment by litlep-nibbyt** [comment]
That's odd -- the columns seem to match. Here's another thing to check: I noticed that the error output you provided says that there is a column named `schema` inside the domain file that's not in the dataframe. The dict inside `parameters.json` file generated by `nist_schemagen` has a key called `schema`.

It appears that you might be using the parameters file instead of the domain file. Try `--domain $PATH_TO_domain` instead of `--domain $PATH_TO_parameters_json`.

**Comment by madi** [comment]
Indeed! Thanks so much, that was it!
